## Кросплатформне програмування Python
### Березюк Євгеній Віталійович
*ІПЗ-23007б*
**Варіант 2**

## Завдання 1.

Завдання 1. Таблиця з формулами відповідно до варіанту наведена нижче.

$$z_{1}=cos~\alpha+sin~\alpha+cos~3\alpha+sin~3\alpha$$
$$z_{2}=2\sqrt{2}cos~\alpha\cdot sin\left(\frac{\pi}{4}+2\alpha\right)$$

In [3]:
import numpy as np

# Задаємо необхідні параметри в коді (наприклад, кут alpha = 30 градусів у радіанах)
alpha = np.pi / 6 

# Обрахунок формул з використанням математичних функцій NumPy
z1 = np.cos(alpha) + np.sin(alpha) + np.cos(3 * alpha) + np.sin(3 * alpha)
z2 = 2 * np.sqrt(2) * np.cos(alpha) * np.sin(np.pi / 4 + 2 * alpha)

# Виводимо результат
print(f"При alpha = {alpha:.4f} радіан:")
print(f"Результат z1: {z1}")
print(f"Результат z2: {z2}")

При alpha = 0.5236 радіан:
Результат z1: 2.3660254037844384
Результат z2: 2.366025403784439


## Завдання 2.

Таблиця з формулами відповідно до варіанту наведена нижче.

$$e^{-x}=\sum_{n=0}^{\infty}\frac{(-1)^{n}x^{n}}{n!}=1-x+\frac{x^{2}}{2!}-\frac{x^{3}}{3!}+\frac{x^{4}}{4!}-..., \quad |x|<\infty$$

In [4]:
import numpy as np
import math

# Необхідні параметри
x = 1.5
precision = 4 # точність (кількість знаків після коми)
eps = 10**(-precision)

# 1. Значення пораховане першим способом (математична функція NumPy)
math_val = np.exp(-x)

# 2. Значення пораховане другим способом (через суму ряду)
series_val = 0.0
n = 0

while True:
    # Формула n-го члена: (-1)^n * x^n / n!
    term = ((-1)**n * x**n) / math.factorial(n)
    series_val += term
    n += 1
    
    # Зупиняємо цикл, якщо поточний член ряду став меншим за задану точність
    if abs(term) < eps:
        break

# Виводимо результат
print(f"Значення пораховане першим способом (NumPy): {round(math_val, precision)}")
print(f"Значення пораховане другим способом (Сума ряду): {round(series_val, precision)}")
print(f"Кількість підсумованих членів ряду: {n}")

Значення пораховане першим способом (NumPy): 0.2231
Значення пораховане другим способом (Сума ряду): 0.2231
Кількість підсумованих членів ряду: 11


## Завдання 3.
Дано цілочислову прямокутну матрицю розмірності 14х12. Матрицю задати в коді програми. Генератор випадкових чисел не використовувати.
1) Визначити кількість стовпців, що не містять жодного нульового елемента.
2) Характеристикою рядка цілочислової матриці назвемо суму її додатних парних елементів. Переставляючи рядки заданої матриці, розташувати їх відповідно до зростання характеристик.

In [ ]:
import numpy as np

# Задаємо цілочислову прямокутну матрицю розмірності 14x12
matrix = np.array([
    [ 1,  2,  3,  0,  4, -2,  6,  8,  9,  1,  2,  3],
    [-2,  4,  6,  8, 10, 12, 14, 16,  0,  2,  4,  6],
    [ 3, -1,  4,  5, -9,  2,  7,  1,  3,  8,  0,  6],
    [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
    [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23], # Немає парних додатних
    [-2, -4, -6, -8,-10,-12,-14,-16,-18,-20,-22,-24], # Лише від'ємні
    [ 4, 10, 14, 20,  0, 30, 34, 40, 44, 50, 54, 60],
    [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
    [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1],
    [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
    [ 6,  7,  0,  9, 10, 11, 12, 13, 14, 15, 16, 17],
    [ 2, -2,  4, -4,  6, -6,  8, -8, 10,-10, 12,-12],
    [ 1,  2,  4,  8, 16, 32, 64, 28, 56, 12, 24, 48]
])

print("Вихідна матриця (14x12):")
print(matrix)

# 1 Визначити кількість стовпців, що не містять жодного нульового елемента.
# Перевіряємо, чи всі елементи в стовпці (axis=0) не дорівнюють нулю
cols_without_zeros = np.all(matrix != 0, axis=0)
num_cols_without_zeros = np.sum(cols_without_zeros)
print(f"\n1 Кількість стовпців, що не містять жодного нульового елемента: {num_cols_without_zeros}")

# 2 Характеристика рядка: сума її додатних парних елементів.
# Створюємо функцію для підрахунку характеристики одного рядка
def row_characteristic(row):
    return np.sum(row[(row > 0) & (row % 2 == 0)])

# Обчислюємо характеристики для всіх рядків матриці
characteristics = np.array([row_characteristic(row) for row in matrix])

print("\nХарактеристики рядків (сума додатних парних елементів):")
for i, char in enumerate(characteristics):
    print(f"Рядок {i+1}: {char}")

# Отримуємо індекси, які відсортують масив характеристик за зростанням
sorted_indices = np.argsort(characteristics)

# Переставляємо рядки матриці відповідно до відсортованих індексів
sorted_matrix = matrix[sorted_indices]

print("\n2 Матриця після перестановки рядків за зростанням характеристик:")
print(sorted_matrix)

Вихідна матриця (14x12):
[[  1   2   3   0   4  -2   6   8   9   1   2   3]
 [ -2   4   6   8  10  12  14  16   0   2   4   6]
 [  3  -1   4   5  -9   2   7   1   3   8   0   6]
 [  2   2   2   2   2   2   2   2   2   2   2   2]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   3   5   7   9  11  13  15  17  19  21  23]
 [ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24]
 [  4  10  14  20   0  30  34  40  44  50  54  60]
 [  2   4   6   8  10  12  14  16  18  20  22  24]
 [ -1   1  -1   1  -1   1  -1   1  -1   1  -1   1]
 [  8   8   8   8   8   8   8   8   8   8   8   8]
 [  6   7   0   9  10  11  12  13  14  15  16  17]
 [  2  -2   4  -4   6  -6   8  -8  10 -10  12 -12]
 [  1   2   4   8  16  32  64  28  56  12  24  48]]

1 Кількість стовпців, що не містять жодного нульового елемента: 0

Характеристики рядків (сума додатних парних елементів):
Рядок 1: 22
Рядок 2: 82
Рядок 3: 20
Рядок 4: 24
Рядок 5: 0
Рядок 6: 0
Рядок 7: 0
Рядок 8: 360
Рядок 9: 156
Рядок 10: 0
Рядок 11: 96
Рядо